stages:
  - build

.gentoo: &gentoo
  image: registry.gitlab.com/grauwoelfchen/portolan/gentoo-amd64-nomultilib:latest

# build {{{
make:
  stage: build
  <<: *gentoo
  before_script:
    - make setup
  script:
    - make build
  cache:
    untracked: true
    key:
      files:
        - .tool/setup-zora
    paths:
      - .tool/zola
  artifacts:
    untracked: true
    paths:
      - dst
    expire_in: 3 days
  only:
    - trunk
    - tags@eloquentlog/eloquentlog-website
# }}}
